sudo: false
dist: trusty
language: node_js

cache: yarn

matrix:
  include:
    - node_js: 6
      env: WEBPACK_VERSION=latest
    - node_js: 8
      env: WEBPACK_VERSION=latest
    - node_js: node
      env: WEBPACK_VERSION=latest
    - node_js: node
      env: WEBPACK_VERSION=webpack/webpack

before_script:
  - yarn add $WEBPACK_VERSION

script:
  - yarn lint
  - yarn test

notifications:
  email: false
